/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransacoesRouteImport } from './routes/transacoes'
import { Route as OrcamentosRouteImport } from './routes/orcamentos'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvestimentosRouteImport } from './routes/investimentos'
import { Route as ContasFixasRouteImport } from './routes/contas-fixas'
import { Route as IndexRouteImport } from './routes/index'

const TransacoesRoute = TransacoesRouteImport.update({
  id: '/transacoes',
  path: '/transacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosRoute = OrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestimentosRoute = InvestimentosRouteImport.update({
  id: '/investimentos',
  path: '/investimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContasFixasRoute = ContasFixasRouteImport.update({
  id: '/contas-fixas',
  path: '/contas-fixas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contas-fixas': typeof ContasFixasRoute
  '/investimentos': typeof InvestimentosRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/orcamentos': typeof OrcamentosRoute
  '/transacoes': typeof TransacoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contas-fixas': typeof ContasFixasRoute
  '/investimentos': typeof InvestimentosRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/orcamentos': typeof OrcamentosRoute
  '/transacoes': typeof TransacoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contas-fixas': typeof ContasFixasRoute
  '/investimentos': typeof InvestimentosRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/orcamentos': typeof OrcamentosRoute
  '/transacoes': typeof TransacoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contas-fixas'
    | '/investimentos'
    | '/login'
    | '/metas'
    | '/orcamentos'
    | '/transacoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contas-fixas'
    | '/investimentos'
    | '/login'
    | '/metas'
    | '/orcamentos'
    | '/transacoes'
  id:
    | '__root__'
    | '/'
    | '/contas-fixas'
    | '/investimentos'
    | '/login'
    | '/metas'
    | '/orcamentos'
    | '/transacoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContasFixasRoute: typeof ContasFixasRoute
  InvestimentosRoute: typeof InvestimentosRoute
  LoginRoute: typeof LoginRoute
  MetasRoute: typeof MetasRoute
  OrcamentosRoute: typeof OrcamentosRoute
  TransacoesRoute: typeof TransacoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transacoes': {
      id: '/transacoes'
      path: '/transacoes'
      fullPath: '/transacoes'
      preLoaderRoute: typeof TransacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos': {
      id: '/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof OrcamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investimentos': {
      id: '/investimentos'
      path: '/investimentos'
      fullPath: '/investimentos'
      preLoaderRoute: typeof InvestimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contas-fixas': {
      id: '/contas-fixas'
      path: '/contas-fixas'
      fullPath: '/contas-fixas'
      preLoaderRoute: typeof ContasFixasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContasFixasRoute: ContasFixasRoute,
  InvestimentosRoute: InvestimentosRoute,
  LoginRoute: LoginRoute,
  MetasRoute: MetasRoute,
  OrcamentosRoute: OrcamentosRoute,
  TransacoesRoute: TransacoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
